language: ruby
rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0

notifications:
  email: false
  slack:
    secure: jlOIVX3b5ot5IjG97PxmtZUr/rXwkWjFt0y5u0hlVQhdZcuipm2jpac2AcAdvuSU+X5eIAgXsRxPGiQkIT6NZgGFpTNEihhO+G3UHbtjhbiaFefOEqqLQLcPDy+CS84gELfTnUGIEIzm2Soemjf5mL0sn858Ce3IRUBy3IgCoqo=
